# Generated by Django 3.0.3 on 2021-01-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
